//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetails
    {
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual tbl_Order tbl_Order { get; set; }
        public virtual tbl_Products tbl_Products { get; set; }
    }
}
